baseURL = "https://pscamodio.github.io/penna-cookbook"
languageCode = "it-it"
title = "Penna CookBook"
publishDir = "docs"
paginate = 10
DefaultContentLanguage = "it"
SectionPagesMenu = "build"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true
pluralizeListTitles = false

[taxonomies]
  ricetta = "ricette"
  tag = "tags"

[sitemap]
  changereq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Raccolta di ricette di Anna e Amodio"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackowerflow = ""
  rss = ""
  background_color_class = "bg-black"
  recent_post_number = 2
  show_reading_time = true

[module]
 [[module.imports]]
  path = "github.com/theNewDynamic/gohugo-theme-ananke"
