baseURL = "https://pscamodio.github.io/penna-cookbook/"
languageCode = "it-it"
title = "Penna CookBook"
publishDir = "docs"
paginate = 10

[module]
 [[module.imports]]
  path = "github.com/theNewDynamic/gohugo-theme-ananke"
